# Generated by Django 4.2.5 on 2023-10-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewtype',
        ),
    ]
